### ISSUE TITLE
Really nice work, Do you have plan to support other file format ? 

### ISSUE THREAD

**Issue by fredq-fu** [JarkkoPFC/meshlete#1]
Really nice work, but I found mlet_gen only supports output file format p3g，do you have any plan to support other file format ? Something like .obj etc.

**Comment by JarkkoPFC** [comment]
obj, etc. do not support meshlets. p3g files are very easy to parse though and there's a doc describing the file format: https://github.com/JarkkoPFC/meshlete/blob/master/doc/file_format_p3g.xlsx
Alternatively you can use the Meshlete lib to build own tools.
