### ISSUE TITLE
Where is the source code for the program itself?

### ISSUE THREAD

**Issue by ElvargThemSelf** [JarkkoPFC/meshlete#2]

**Comment by JarkkoPFC** [comment]
There's quite large body of work to just parse different 3D formats (obj/fbx/dae/etc.) so it's not included in this project. For the parsing I used my custom implementation for different 3D asset files, and ripping the parsers from my larger code base would be quite a big effort ("You wanted a banana but you got a gorilla holding the banana") and there are better alternatives anyway (e.g. https://github.com/assimp/assimp). However, I just pushed export_p3g() implementation to export p3g files, and complemented the sample project to show how to use it.

**Comment by JarkkoPFC** [comment]
Good news, the gorilla has been delivered, just committed the tool sources 😄 🦍
